### ISSUE TITLE
Fine-tune on a new task

### ISSUE THREAD

**Issue by PlusStar-Li** [releaunifreiburg/FSBO#1]
I can not find the implementation of the fine-tune process on a new task in this repo, is there any other repo of this paper?

**Comment by sebastianpinedaar** [comment]
Thanks for your interest!
Assuming that you refer to a new dataset as a "task", the fine-tuning happens inside the `train` method in the class `DeepKernelGP`.

https://github.com/releaunifreiburg/FSBO/blob/b4fbaaeac2fe7a3a2c6c05a222b028371123c3c9/fsbo_modules.py#L70
